### ISSUE TITLE
Fix "Foods Typically Available"

### ISSUE THREAD

**Issue by Michaelmvv** [jointheleague/lets-eat#132]
We’ve determined that there will be only a few taxonomy for the “Foods Typically Available”.  Can we have this be a set of checkboxes (where multiple options may be checked)?  We’d want it to appear in the table and pin with commas between each of the items listed.  Here are the defined options:
·         20 to 30 pounds of fresh produce
·         Canned and boxed foods
·         Bread and pastries
·         Cooked meal
·         Snacks
·         30 pound box of government canned and dry foods with a 5 pound block of cheese
·         Government canned and dry foods, with occasional frozen meats, produce, or dairy
·         Dairy
·         Fresh Produce
·         Grocery store donations (may include meat, dairy, pastries, salads, and more)

**Comment by philcruz** [comment]
This is not working. I have latest master (as of today), did a git reset and I'm seeing

http://www.screencast.com/t/gKoG0V59Ntq0

To clarify, the strings in the foods object in the database are not the strings to display to the end user. If the foods object is {"produce": true, "cooked": true, ...} it should display "20 to 30 pounds of fresh produce, Cooked meal".

**Comment by philcruz** [comment]
This is done.
