### ISSUE TITLE
add locations via the interface

### ISSUE THREAD

**Issue by philcruz** [jointheleague/lets-eat#29]
You should be able to add new locations via the admin interface. 
These need to be geocoded.

**Comment by najclark** [comment]
My commit adds a button to the admin panel to geocode things from the panel.

**Comment by philcruz** [comment]
Where is the button? Can you take a screenshot to show where it's supposed to be?

**Comment by najclark** [comment]
![screenshot from 2016-03-21 22-18-56](https://cloud.githubusercontent.com/assets/11011325/13942813/83dce80e-efb3-11e5-9648-250f27b877b0.png)

**Comment by philcruz** [comment]
I added a location "Test" and I don't see the button and my lat/long is set to 0/0 even though I left those fields blank.

http://screencast.com/t/jCIK237H4X0y

**Comment by najclark** [comment]
It isn't merged into the master branch it is in caching_markers.

**Comment by najclark** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/11011325/13942980/9947b992-efb5-11e5-8549-5cf2eb969d8a.png)

**Comment by philcruz** [comment]
Yeah, that's the branch I have checked out but not seeing those buttons.
