### ISSUE TITLE
Find by Zip Code

### ISSUE THREAD

**Issue by Michaelmvv** [jointheleague/lets-eat#3]
Also get rid of "Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/?zipcode=--zipCodeHere--.""

**Comment by Michaelmvv** [comment]
Perhaps add a current location marker?

**Comment by philcruz** [comment]
If you can show the current location of the user that would be cool/nice to have. 

The "oops, no route..." is a separate issue from "find by zipcode" so I'll create an issue for that.

**Comment by philcruz** [comment]
zip code search is working. creating an issue for the enhancement to show the current location.
