### ISSUE TITLE
Make html more printer-friendly

### ISSUE THREAD

**Issue by najclark** [jointheleague/lets-eat#44]
Right now the map doesn't show up when you print.
![selection_002](https://cloud.githubusercontent.com/assets/11011325/14191891/307d3468-f74f-11e5-9b34-f6464799bfef.png)

**Comment by philcruz** [comment]
Maybe this will help

http://stackoverflow.com/questions/32790057/google-map-canvas-is-getting-blank-when-printing-ctrl-p
